### ISSUE TITLE
Unable to import from simple_lock

### ISSUE THREAD

**Issue by MStokholm** [0h-n0/simple-lock#2]
I got the following error when trying to use simple-lock for the first time in Python 3.7 on a windows machine.

> ImportError: cannot import name 'lock' from 'simple_lock' 

The same error occurs with all the given examples in the readme. 

> ImportError: cannot import name 'watch' from 'simple_lock'

**Comment by 0h-n0** [comment]
Thank you for reporting. I was wrong to upload a package.

Please check the latest version.

```shell
$ pip install -U simple-lock
$ python -c 'from simple_lock import lock, watch'
```
